version: '3'

services:
  app:
    container_name: django
    build: ./django
    volumes:
     - ./django/code/:/code
    ports:
     - 80:80
    command: python mysite/manage.py runserver 0.0.0.0:80
    depends_on:
      - db
  db:
    container_name: mysql
    build: ./mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'django'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'django'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    privileged: true
